IMAGE_EXTENSION = ".png"
APP_PREFIX = "app/"
SUDOKUS_FILE_PATH = "static/sudokus/"
SOLVED_SUDOKU_PREFIX = "solved"
UNSOLVED_SUDOKU_PREFIX = "unsolved"

SOLVED_SUDOKU_PATH = SUDOKUS_FILE_PATH + SOLVED_SUDOKU_PREFIX + IMAGE_EXTENSION
UNSOLVED_SUDOKU_PATH = SUDOKUS_FILE_PATH + UNSOLVED_SUDOKU_PREFIX + IMAGE_EXTENSION
