IMAGE_EXTENSION = ".png"
SUDOKUS_FILE_PATH = "app/static/sudokus/"
SOLVED_SUDOKU_PREFIX = "solved"
UNSOLVED_SUDOKU_PREFIX = "unsolved"

SOLVED_SUDOKU_PATH = SUDOKUS_FILE_PATH + SOLVED_SUDOKU_PREFIX + IMAGE_EXTENSION
UNSOLVED_SUDOKU_PATH = SUDOKUS_FILE_PATH + UNSOLVED_SUDOKU_PREFIX + IMAGE_EXTENSION
