IMAGE_EXTENSION = ".png"
SUDOKUS_FILE_PATH = "app/static/sudokus/"
SOLVED_SUDOKU_PREFIX = "solved"
UNSOLVED_SUDOKU_PREFIX = "unsolved"

EMPTY_FRAME_FILE_PATH = SUDOKUS_FILE_PATH + "empty" + IMAGE_EXTENSION
